spring.application.name=blur

spring.datasource.url=jdbc:mysql://localhost:3306/blur
spring.datasource.username=root
spring.datasource.password=Phamsy@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true